version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./src:/home/node/app/src
      - ./node_modules/:/home/node/app/node_modules
      - ./package.json:/home/node/app/package.json
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./knexfile.js:/home/node/app/knexfile.js
      - ./.env:/home/node/app/.env
    networks:
      - api-network
    command: yarn watch
    depends_on:
      - api-postgresql


  api-postgresql:
    container_name: api-postgresql
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apidb
    networks:
      - api-network

  api-adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - api-postgresql
    networks:
      - api-network
networks:
  api-network:
